name: flutter_compose
description: "Inspired by Vue Composables, flutter_compose offers a streamlined way to create reusable components in Flutter. Improve code organization and reduce boilerplate."
version: 0.0.5
homepage: "https://sequencode.dev/"
repository: "https://github.com/sequencode/flutter_compose"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

